apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: cilium-values
    namespace: cluster-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml