apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
            containers:
              - name: hello-app
                image: juwisnie/hello-app:1.0.7 # {"$imagepolicy": "cluster-config:hello-policy"}
                ports:
                  - containerPort: 80
                resources:
                  limits:
                    cpu: "0.5"
                    memory: "512Mi"
                  requests:
                    cpu: "0.1"
                    memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
  name: hello-app
  namespace: hello
spec:
  selector:
    app: hello-app
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
