apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hello-app.yaml
images:
- name: juwisnie/hello-app
  newName: juwisnie/hello-app # {"$imagepolicy": "cluster-config:hello-policy"}
  newTag: 1.0.7 # {"$imagepolicy": "cluster-config:hello-policy:tag"}
  