apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  creationTimestamp: "2024-04-02T14:53:43Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: cluster-config-infra
    kustomize.toolkit.fluxcd.io/namespace: cluster-config
  name: redis
  namespace: cluster-config
  resourceVersion: "59528"
  uid: d4a27d30-0c39-4a0f-9bc3-c63370bc0cad
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: 17.x
  install:
    remediation:
      retries: 3
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: redis
  valuesFrom:
  - kind: ConfigMap
    name: redis-values-mhbkt4gc9t
status:
  conditions:
  - lastTransitionTime: "2024-04-02T14:58:50Z"
    message: install retries exhausted
    reason: InstallFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-04-02T14:58:50Z"
    message: |-
      Helm install failed: context deadline exceeded

      Last Helm logs:

      creating 10 resource(s)
      beginning wait for 10 resources with timeout of 5m0s
      StatefulSet is not ready: redis/redis-master. update has not yet been observed
      StatefulSet is not ready: redis/redis-master. 0 out of 1 expected pods have been scheduled
      StatefulSet is not ready: redis/redis-master. 0 out of 1 expected pods are ready
    reason: InstallFailed
    status: "False"
    type: Released
  failures: 19
  helmChart: cluster-config/cluster-config-redis
  installFailures: 4
  lastAttemptedRevision: 17.17.1
  lastAttemptedValuesChecksum: 4f71db1d16f3c07bfcc163629b1cdf5f5a0552b4
  lastReleaseRevision: 1
  observedGeneration: 1
